services:
  - type: web
    name: tttttt
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: OWNER_ID
        value: 7953403242
      - key: GROUP_ID
        value: -1003344849078
